# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 242512078e823b05dedf98445fa53d06069e42901c0f9084df924382a73def449f26468a6170c2759658f21fd8ae2f6a78e935cff95dad8bf0da3bbe67643b9a
  VK_KEY: '5767362'
  VK_SECRET: sOEKEpbxYHX1VFRZlwgb

test:
  secret_key_base: 11048a3cfc31e2a97d15f4064a965bfefb75ef7c2f229c6150aa7941442f66ea8eb32f2b2278ff51fdd6dc6ab31ac28df73a35c7543c3bde54729c41b4b3c87f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
